// Install OUTPUT manifest — `plugin/.gitignore`, generated, never hand-edited.
//
// `plugin/` is the framework's tracked capability tree AND, in a bound clone, the tree the picked
// pack is installed into. Both kinds of file live at the same paths, so git alone cannot tell
// "framework content" from "what my install copied here". Until this existed they sat
// untracked-but-not-ignored: `??` noise in every status, and one broad `git add` could publish a
// single project's installed pack as framework content (it did — 18 files).
//
// The writers are the only components that KNOW what they wrote, so they declare it. Two of them:
// the domain installer (install-capabilities.js) and the learning scaffolder (ensure-library.js,
// called later by doctor/promote). The installer OWNS the manifest — it writes it fresh on every
// run, so a path the pack stops shipping stops being ignored and its stale copy reappears as
// untracked. The scaffolder only ADDS to an existing manifest.
//
// That last rule is what keeps the framework trunk correct: an unbound checkout has no manifest,
// so scaffolds created there stay visible and get committed as framework content — which is
// exactly what they are when no pack is installed.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const MANIFEST = ".gitignore";
const HEADER = (/** @type {string} */ domainName) => [
  "# GENERATED by the install (ui/server/cli/install-capabilities.js) — do not hand-edit.",
  `# Files the '${domainName}' pack install wrote into this tree. They are OUTPUT: the source of`,
  "# truth is domains/<pack>/plugin/, and re-running the install regenerates them and this list.",
  "# Ignored so a broad `git add` can never publish one project's install as framework content.",
  "# A path that leaves the pack leaves this list, and its stale copy shows up as untracked",
  "# again — visible, not silently masked.",
  MANIFEST,
];

// A manifest line is a PATTERN, not a literal path, so a filename carrying gitignore syntax could
// widen a rule to files the install never wrote — a newline splits one entry into two, `*` matches
// siblings, `!` re-includes. Install output must only ever hide itself, so every entry is anchored
// to the plugin root (leading `/`) and any metacharacter is escaped. Names that cannot be expressed
// safely at all (control characters) are rejected outright — `preflightPack` in the installer and
// `check:install-paths` reject them earlier, before a single file is written; this is the last line.
const UNSAFE_CHARS = /[\n\r\0]/;

/** One safe, exactly-matching manifest entry for a plugin-relative path. @param {string} rel */
function toEntry(rel) {
  if (UNSAFE_CHARS.test(rel))
    throw new Error(
      `install output path contains a control character and cannot be safely declared: ${JSON.stringify(rel)}`,
    );
  return "/" + rel.replace(/[[\]*?!#\\]/g, (c) => "\\" + c);
}

/** @param {string} pluginDir @param {string[]} absPaths @returns {string[]} anchored, escaped entries */
function toRelative(pluginDir, absPaths) {
  return absPaths.map((f) => toEntry(path.relative(pluginDir, f).split(path.sep).join("/")));
}

/** Write the manifest fresh — the installer's call. Replaces any previous list, so the file always
 * describes THIS install rather than accumulating history.
 * @param {string} pluginDir @param {string} domainName @param {string[]} absPaths */
export function writeInstallOutput(pluginDir, domainName, absPaths) {
  const entries = [...new Set(toRelative(pluginDir, absPaths))].sort((a, b) => a.localeCompare(b));
  writeFileSync(path.join(pluginDir, MANIFEST), [...HEADER(domainName), ...entries, ""].join("\n"));
}

/** Add paths to an EXISTING manifest — for output written after the install (learning scaffolds).
 * No manifest means no pack is installed here (the framework trunk), so this is a no-op and the
 * paths stay visible for committing. Idempotent.
 * @param {string} pluginDir @param {string[]} absPaths */
export function addInstallOutput(pluginDir, absPaths) {
  const file = path.join(pluginDir, MANIFEST);
  if (!existsSync(file) || absPaths.length === 0) return;
  const lines = readFileSync(file, "utf8").split("\n");
  const header = lines.filter((l) => l.startsWith("#"));
  const existing = lines.filter((l) => l && !l.startsWith("#"));
  const entries = [...new Set([...existing, ...toRelative(pluginDir, absPaths)])].sort((a, b) =>
    a.localeCompare(b),
  );
  writeFileSync(file, [...header, ...entries, ""].join("\n"));
}
